
class TOU:
    @staticmethod
    def Load_TOU():
        return  """Terms of Use for the “Hossanna” Application (Stock Market Prediction Version)

    
    Last updated: [29.11.2025]
    
    1. General Provisions
    These Terms of Use (“Terms”) define the rules for using the “Hossanna”
    application (“Application”), designed to present and analyze stock
    market data, including generating predictions based on analytical
    algorithms. The Application is an academic project, created for the
    purpose of completing a university semester assignment. By using the
    Application, the user accepts these Terms. If the user does not agree
    to the Terms, they must stop using the Application.
    
    2. Nature and Purpose of the Application
    The Application is intended to demonstrate algorithms for analyzing
    and forecasting stock market data in an educational environment.
    The Application is not a tool for investment advising, financial
    consulting, brokerage services, or economic decision-making.
    Any data, analysis results, predictions, or alerts generated by the
    Application are informational and educational only.
    None of the information provided by the Application constitutes
    investment recommendations, financial advice, profit guarantees,
    or encouragement to buy or sell financial instruments.
    Users should make investment decisions solely based on their own
    analysis and/or by consulting a licensed investment advisor.
    
    3. Technical Requirements and Used Libraries
    The Application requires a Python environment and certain system
    and graphical libraries. The Application uses:
    sys, os, ctypes, pathlib.Path, PySide6.QtWidgets,
    PySide6.QtCore, PySide6.QtGui.
    Functionality may depend on system configuration.
    
    4. License to Use
    The user is granted a non-exclusive, limited license for educational
    purposes. It is prohibited to modify, distribute, or commercially
    use the Application without permission.
    
    5. Limitations Regarding Stock Market Content
    Predictions are based on simplified models.
    Results may be inaccurate and not reflect actual market conditions.
    The Application does not use licensed market data.
    Predictions must not be used for real investment decisions.
    
    6. Limitation of Liability
    The Application is provided “as is”.
    The author is not responsible for financial losses or damages caused
    by the Application.
    
    7. User Data and Privacy
    The Application does not collect personal data unless stated otherwise.
    
    8. Intellectual Property
    The Application and its components are the author’s property.
    
    9. Updates
    The author may introduce updates requiring new Terms acceptance.
    
    10. Contact
    For matters related to the Application: [insert email].
    """

